Add start shift logic
veniaventis/hookah_space_bot pull request #2
Opened 2024-11-28 13:27 UTC by dodik2233

2024-11-28 13:29 UTC, veniaventis requested changes

2024-11-28 13:29 UTC, veniaventis commented on config.py
> +TOKEN = getenv("7325741524:AAFXbzzghj6IOeUUVAzp4LPiGRKo98ttbMg")
Нельзя хранить данные авторизции на гит
Измени на переменную окржуения

2024-11-28 13:29 UTC, veniaventis commented on hookah_space_bot.py
> +    bot = Bot(token="7325741524:AAFXbzzghj6IOeUUVAzp4LPiGRKo98ttbMg", default=DefaultBotProperties(parse_mode=ParseMode.HTML))
как выше

2024-11-28 15:10 UTC, veniaventis commented on keyboards/order_keyboard.py
> +
Нам нужен этот закоментированный код?

2024-11-28 15:10 UTC, veniaventis commented on routers/commands/order_commands.py
> +@router.message(Command("order"), F.from_user.id.in_({5477880310,1614891721}))
Нужно добавить фильтр на пользователя

2024-11-28 15:10 UTC, veniaventis commented on routers/commands/order_commands.py
> +@router.message(Command("order"), F.from_user.id.in_({5477880310,1614891721}))
Так же нужно добавить фильтра Команду можно вызвать только если смены открыта

2024-11-28 15:10 UTC, veniaventis commented on routers/commands/order_commands.py
нужно еще добавить обслуживание кнопок назад

2024-11-29 13:04 UTC, dodik2233 commented on routers/commands/order_commands.py
это оказалось сложнее чем предполагалось

2024-12-08 09:13 UTC, closed without merging